services:
  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
    networks:
      - rag_net
    restart: always

  node1:
    image: project-worker:latest
    build: .
    container_name: worker_1
    env_file:
      - .env
    environment:
      - NUM_WORKERS=${NODE1_NUM_WORKERS}
      - GPU_SERVERS=${GPU_SERVERS_1}
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - rag_net
    restart: always
  node2:
    image: project-worker:latest
    build: .
    container_name: worker_2
    env_file:
      - .env
    environment:
      - NUM_WORKERS=${NODE2_NUM_WORKERS}
      - GPU_SERVERS=${GPU_SERVERS_2}
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - rag_net
    restart: always

networks:
  rag_net:
    driver: bridge
