services:
  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - rag_net
    restart: always

  node1:
    image: project-worker:latest
    build: .
    container_name: worker_1
    env_file:
      - RAG_system/.env
    environment:
      - NUM_WORKERS=1
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - rag_net
    restart: always

  node2:
    image: project-worker:latest
    container_name: worker_2
    env_file:
      - RAG_system/.env
    environment:
      - NUM_WORKERS=1
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - rag_net
    restart: always

  node3:
    image: project-worker:latest
    container_name: worker_3
    env_file:
      - RAG_system/.env
    environment:
      - NUM_WORKERS=1
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - rag_net
    restart: always

networks:
  rag_net:
    driver: bridge
